disabled_rules:
  - large_tuple
  - identifier_name
  - type_name
  - force_cast
  - file_length
  - function_parameter_count
  - todo
  - nesting
  - block_based_kvo
function_body_length:
  warning: 50
  error: 60
line_length: 
  ignores_comments: true

